
dict = {'Jumping Jacks' : 0,
        'Squats' : 1,
        'Squat Jumps' : 2,
        'Burpees' : 3,
        'Push-ups' : 4,
        'Mountain Climbers' : 5,
        'Plank' : 6,
        'Wall Push-ups' : 7,
        'Brisk walking' : 8,
        'Ankle Circles' : 9,
        'Side-lying leg lifts' : 10,
        'Seated Marches' : 11,
        'Cobra Stretch' : 12,
        'Jump Rope' : 13,
        'Glute Bridges' : 14,
        'Knee Extensions' : 15,
        'Seated Leg Lifts' : 16,
        'Seated Rows' : 17,
        'Lunges' : 18,
        'Seated Knee Lifts' : 19,
        'Chair Squats' : 20,
        'Heel raises' : 21,
        'Step-Ups' : 22,
        'Leg lifts' : 23,
        'Standing Hip Abduction' : 24,
        'Seated Arm Raises' : 25,
        'Knee Raises' : 26,
        'Reverse Lunges' : 27,
        'Bird Dogs' : 28,
        'Calf Raises' : 29,
        'Bicycle Crunches' : 30,
        'Scissors Jump': 31,
        'Single-Leg Squat': 32,
        'Squat Isometric Hold': 33,
        'Diamond Push-ups': 34,
        'Single-Leg Burpees': 35
}

filter = {
    'not_for_old' : ['Squat Jumps','Burpees','Mountain Climbers','Jump Rope'],
    'for_female' : ['Ankle Circles','Side-lying leg lifts','Cobra Stretch','Glute Bridges',
                    'Seated Leg Lifts','Reverse Lunges','Bird Dogs','Chair Squats' ],
    'for_male&female' : ['Jumping Jacks','Plank','Squats','Bicycle Crunches','Mountain Climbers','Step-Ups','Lunges'
                        'Leg lifts','Single-Leg Squat','Push-ups','Calf Raises'],

    'for_advanced' : ['Scissors Jump','Single-Leg Squat','Squat Isometric Hold','Diamond Push-ups','Single-Leg Burpees'],
    'for_beginner' : ['Brisk walking','Wall Push-ups','Seated Marches','Cobra Stretch','Knee Extensions',
                    'Seated Leg Lifts','Seated Rows','Chair Squats','Plank','Glute Bridges',
                    'Heel raises','Calf Raises','Seated Arm Raises','Knee Raises'],

    'for_fat' : ['Brisk walking','Ankle Circles','Wall Push-ups','Seated Marches','Glute Bridges',
                'Knee Extensions','Seated Leg Lifts','Calf Raises','Bicycle Crunches','Chair Squats'],

    'for_weight_loss' : ['Jumping Jacks','Squats','Squat Jumps','Burpees','Push-ups','Mountain Climbers',
                        'Plank','Wall Push-ups','Brisk walking','Jump Rope','Bicycle Crunches',
                        'Scissors Jump','Single-Leg Burpees'],
    'for_muscle_gain' : ['Squats','Squat Jumps','Push-ups','Plank','Glute Bridges','Knee Extensions',
                        'Lunges','Seated Knee Lifts','Chair Squats','Heel raises','Step-Ups','Leg lifts',
                        'Standing Hip Abduction','Bird Dogs','Calf Raises','Bicycle Crunches',
                        'Seated Rows','Single-Leg Squat','Squat Isometric Hold','Diamond Push-ups'],
    'for_fit' : ['Brisk walking','Ankle Circles','Side-lying leg lifts','Seated Marches','Cobra Stretch',
                'Seated Leg Lifts','Seated Arm Raises','Knee Raises','Reverse Lunges','Wall Push-ups','Mountain Climbers'],

    'not_for_diabetes' : ['Burpees','Jump Rope','Squat Jumps','Single-Leg Squat','Squat Isometric Hold'],
    'for_diabetes' : ['Brisk walking','Squats','Push-ups','Lunges','Plank','Glute Bridges','Seated Rows'],

    'not_for_hbp' : ['Burpees','Squat Jumps','Diamond Push-ups','Single-Leg Burpees'],
    'for_hbp' : ['Brisk walking','Ankle Circles','Wall Push-ups','Seated Marches','Glute Bridges'],

    'not_for_cholesterol' : ['Jumping Jacks','Squat Jumps','Burpees','Mountain Climbers'],
    'for_cholesterol' : ['Brisk walking','Squats','Push-ups','Plank','Lunges' ],

    'not_for_heart'  : ['Burpees','Squat Jumps','Mountain Climbers','Jumping Jacks'],
    'for_heart' : ['Brisk walking','Ankle Circles','Wall Push-ups','Seated Marches','Glute Bridges'],

    'not_for_digestive' : ['Jumping Jacks','Squat Jumps','Burpees','Mountain Climbers'],
    'for_digestive' : ['Brisk walking','Wall Push-ups','Plank','Seated Marches','Glute Bridges','Ankle Circles','Cobra Stretch'],

    'not_for_osteo' : ['Jumping Jacks','Squat Jumps','Burpees','Mountain Climbers','Jump Rope','Reverse Lunges','Single-Leg Burpees'],
    'for_osteo' : ['Brisk walking','Squats','Lunges','Step-Ups','Glute Bridges','Wall Push-ups','Seated Rows'],

    'not_for_arthritis' : ['Burpees','Mountain Climbers','Jump Rope','Lunges','Squat Jumps','Side-lying leg lifts'],
    'for_arthritis' : ['Brisk walking','Seated Marches','Seated Leg Lifts','Bird Dogs','Chair Squats','Plank'],

    'not_for_copd' : ['Scissors Jump','Single-Leg Burpees','Side-lying leg lifts','Jump Rope','Mountain Climbers','Jumping Jacks','Squat Jumps','Burpees'],
    'for_copd' : ['Brisk walking','Seated Marches','Chair Squats','Wall Push-ups','Plank','Seated Rows','Cobra Stretch','Glute Bridges','Knee Extensions'],

    'not_for_stroke' : ['Jumping Jacks','Squat Jumps','Burpees','Mountain Climbers','Jump Rope','Lunges','Reverse Lunges',
                        'Single-Leg Squat','Squat Isometric Hold','Step-Ups'],
    'for_stroke' : ['Brisk walking','Seated Marches','Chair Squats','Plank','Seated Rows','Cobra Stretch','Glute Bridges',
                    'Knee Extensions','Bird Dogs','Standing Hip Abduction','Ankle Circles'],

}

medCond = {'None':-1,
        'Healthy':0,
        'Diabetes':1,
        'High blood pressure':2,
        'High cholesterol':3,
        'Heart disease':4,
        'Digestive disorders':5,
        'Osteoporosis':6,
        'Arthritis':7,
        'COPD':8,
        'Stroke':9}

allWorkouts = {
0 : {'Brisk walking'},
1 : {'Seated Marches', 'Wall Push-ups', 'Chair Squats', 'Seated Rows', 'Cobra Stretch', 'Glute Bridges', 'Brisk walking', 'Plank', 'Knee Extensions'},
2 : {'Seated Marches', 'Bird Dogs', 'Ankle Circles', 'Chair Squats', 'Seated Rows', 'Cobra Stretch', 'Glute Bridges', 'Brisk walking', 'Plank', 'Standing Hip Abduction', 'Knee Extensions'},
3 : {'Brisk walking', 'Wall Push-ups'},
4 : {'Brisk walking', 'Plank'},
5 : {'Seated Marches', 'Bird Dogs', 'Chair Squats', 'Brisk walking', 'Plank', 'Seated Leg Lifts'},
6 : {'Seated Marches', 'Wall Push-ups', 'Ankle Circles', 'Glute Bridges', 'Brisk walking'},
7 : {'Ankle Circles'},
8 : {'Wall Push-ups', 'Seated Rows', 'Step-Ups', 'Glute Bridges', 'Brisk walking', 'Lunges', 'Squats'},
9 : {'Seated Marches', 'Glute Bridges', 'Brisk walking', 'Wall Push-ups'},
10 : {'Plank', 'Brisk walking', 'Wall Push-ups'},
11 : {'Seated Marches', 'Wall Push-ups', 'Ankle Circles', 'Cobra Stretch', 'Glute Bridges', 'Brisk walking', 'Plank'},
12 : {'Glute Bridges', 'Brisk walking'},
13 : {'Knee Raises', 'Seated Marches', 'Wall Push-ups', 'Heel raises', 'Chair Squats', 'Seated Rows', 'Cobra Stretch', 'Glute Bridges', 'Seated Arm Raises', 'Brisk walking', 'Plank', 'Seated Leg Lifts', 'Knee Extensions', 'Calf Raises'},
14 : {'Push-ups', 'Squats'},
15 : {'Glute Bridges', 'Brisk walking', 'Wall Push-ups'},
16 : {'Seated Marches', 'Wall Push-ups', 'Chair Squats', 'Glute Bridges', 'Brisk walking', 'Seated Leg Lifts', 'Knee Extensions', 'Calf Raises'},
17 : {'Single-Leg Burpees', 'Squat Isometric Hold', 'Diamond Push-ups', 'Single-Leg Squat', 'Bicycle Crunches', 'Scissors Jump'},
18 : {'Seated Marches', 'Brisk walking'},
19 : {'Single-Leg Burpees', 'Squat Isometric Hold', 'Diamond Push-ups', 'Ankle Circles', 'Single-Leg Squat', 'Bicycle Crunches', 'Scissors Jump'},
20 : {'Squats'},
21 : {'Seated Marches', 'Glute Bridges', 'Brisk walking'},
22 : {'Leg lifts', 'Push-ups', 'Squat Isometric Hold', 'Mountain Climbers', 'Diamond Push-ups', 'Squat Jumps', 'Ankle Circles', 'Seated Knee Lifts', 'Step-Ups', 'Reverse Lunges', 'Standing Hip Abduction', 'Bicycle Crunches', 'Lunges', 'Squats', 'Single-Leg Burpees', 'Bird Dogs', 'Single-Leg Squat', 'Side-lying leg lifts', 'Scissors Jump'},
23 : {'Seated Rows', 'Glute Bridges', 'Brisk walking', 'Plank'},
24 : {'Single-Leg Burpees', 'Push-ups', 'Squat Isometric Hold', 'Mountain Climbers', 'Bird Dogs', 'Diamond Push-ups', 'Ankle Circles', 'Step-Ups', 'Reverse Lunges', 'Single-Leg Squat', 'Bicycle Crunches', 'Side-lying leg lifts', 'Scissors Jump', 'Squats'},
25 : {'Push-ups', 'Seated Rows', 'Glute Bridges', 'Brisk walking', 'Plank', 'Lunges', 'Squats'},
26 : {'Push-ups', 'Squat Isometric Hold', 'Mountain Climbers', 'Diamond Push-ups', 'Bicycle Crunches', 'Jumping Jacks', 'Squats', 'Single-Leg Burpees', 'Single-Leg Squat', 'Scissors Jump'},
27 : {'Single-Leg Burpees', 'Push-ups', 'Squat Isometric Hold', 'Mountain Climbers', 'Squat Jumps', 'Diamond Push-ups', 'Burpees', 'Single-Leg Squat', 'Jump Rope', 'Bicycle Crunches', 'Jumping Jacks', 'Scissors Jump', 'Squats'},
28 : {'Bird Dogs'},
29 : {'Seated Marches', 'Chair Squats', 'Seated Rows', 'Cobra Stretch', 'Glute Bridges', 'Brisk walking', 'Plank', 'Knee Extensions'},
30 : {'Seated Rows', 'Glute Bridges', 'Brisk walking', 'Wall Push-ups'},
31 : {'Seated Marches', 'Wall Push-ups', 'Cobra Stretch', 'Glute Bridges', 'Brisk walking', 'Plank'},
32 : {'Push-ups', 'Lunges', 'Squats'},
33 : {'Bicycle Crunches', 'Jumping Jacks', 'Push-ups', 'Squats'},
34 : {'Seated Marches', 'Chair Squats', 'Brisk walking', 'Plank', 'Seated Leg Lifts'},
35 : {'Seated Marches', 'Chair Squats', 'Glute Bridges', 'Brisk walking', 'Knee Extensions'},
36 : {'Bicycle Crunches', 'Ankle Circles'},
37 : {'Bicycle Crunches'},
38 : {'Seated Marches', 'Wall Push-ups', 'Chair Squats', 'Glute Bridges', 'Brisk walking', 'Knee Extensions'},
39 : {'Seated Rows', 'Glute Bridges', 'Brisk walking'},
40 : {'Chair Squats', 'Seated Leg Lifts', 'Seated Marches', 'Brisk walking'},
41 : {'Chair Squats', 'Seated Marches', 'Brisk walking', 'Plank'},
42 : {'Standing Hip Abduction', 'Ankle Circles', 'Bird Dogs'},
43 : {'Ankle Circles', 'Bird Dogs'},
44 : {'Step-Ups', 'Lunges', 'Squats'},
45 : {'Push-ups', 'Bird Dogs', 'Ankle Circles', 'Step-Ups', 'Reverse Lunges', 'Bicycle Crunches', 'Side-lying leg lifts', 'Squats'},
46 : {'Leg lifts', 'Push-ups', 'Bird Dogs', 'Ankle Circles', 'Seated Knee Lifts', 'Step-Ups', 'Reverse Lunges', 'Standing Hip Abduction', 'Bicycle Crunches', 'Side-lying leg lifts', 'Lunges', 'Squats'},
47 : {'Step-Ups', 'Squats'},
48 : {'Chair Squats', 'Seated Marches', 'Brisk walking'},
49 : {'Glute Bridges', 'Brisk walking', 'Plank'},
50 : {'Seated Marches', 'Cobra Stretch', 'Glute Bridges', 'Brisk walking', 'Plank'},
51 : {'Seated Marches', 'Brisk walking', 'Plank'},
52 : {'Lunges', 'Squats'},
}
